spring:
  application:
    name: Test
    
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/xe
#    username: Test
#    password: 123456
#    driver-class-name: oracle.jdbc.OracleDriver
  
  h2:
    console:
      enabled: true
      path: /console
    
  datasource:
    url: jdbc:h2:mem:testdb;Mode=Oracle
    driver-class-name: org.h2.Driver 
    username: sa 
    password: 123456 
 
 
server:
  port: 8091
  
# call coindesk url
coindeskUrl: https://api.coindesk.com/v1/bpi/currentprice.json