spring:
  application:
    name: Test
    
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: Test
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
 
 
server:
  port: 8091