DROP SEQUENCE SEQ_CURRENCY;
DROP TABLE CURRENCY_ENTITY;

CREATE TABLE CURRENCY_ENTITY( 		
	ID            NUMBER(22)          NOT NULL,	
	CODE          NVARCHAR2(22)       NOT NULL,	
	CODE_CHN      NVARCHAR2(22)       NOT NULL,	
	UPDATE_USER          NVARCHAR2(10)          NOT NULL,	
	UPDATE_DATE          TIMESTAMP     DEFAULT     SYSTIMESTAMP      NOT NULL
		);
		
ALTER TABLE CURRENCY_ENTITY ADD CONSTRAINT PK_CURRENCY_ID PRIMARY KEY (ID);

CREATE SEQUENCE SEQ_CURRENCY NOCACHE MAXVALUE 9223372036854770000 START WITH 1;

COMMIT;